from typing import Any


def generate_readme(project: dict[str, Any]) -> str:
    scan = project.get("scan_result", {})
    tech = scan.get("tech_stack", {})
    api_map = scan.get("api_map", {})
    bugs = scan.get("bugs", {})
    database_map = scan.get("database_map", {})
    improvements = scan.get("improvements", {})
    name = project.get("name", "Project")
    detected = ", ".join(tech.get("detected", [])) or "Not detected yet"
    languages = tech.get("languages", scan.get("languages", {}))
    language_lines = "\n".join(f"- {language}: {count} files" for language, count in sorted(languages.items(), key=lambda x: x[1], reverse=True)[:12])
    endpoint_lines = "\n".join(
        f"- `{','.join(endpoint['methods'])} {endpoint['path']}` in `{endpoint['handler_file']}`"
        for endpoint in api_map.get("endpoints", [])[:40]
    ) or "- No API endpoints detected by static scan."
    manifest_lines = "\n".join(f"- `{manifest['path']}`" for manifest in tech.get("manifests", [])[:25]) or "- No manifest files detected."
    issue_summary = bugs.get("summary", {})

    return f"""# {name}

Generated by AI Codebase Explainer.

## Overview

This repository contains {scan.get("file_count", 0)} files across {scan.get("folder_count", 0)} folders.

Detected stack: {detected}

## Languages

{language_lines or "- No indexed language information available."}

## Project Structure

The repository scanner indexed source files, extracted imports, symbols, API routes, dependency relationships, and semantic code chunks for grounded AI chat.

## Manifests and Dependency Inputs

{manifest_lines}

## API Surface

{endpoint_lines}

## Database Signals

{database_map.get("summary", "No database relationships detected by static scan.")}

## Quality and Security Snapshot

- Quality score: {bugs.get("score", "N/A")}
- Critical issues: {issue_summary.get("Critical", 0)}
- High issues: {issue_summary.get("High", 0)}
- Medium issues: {issue_summary.get("Medium", 0)}
- Low issues: {issue_summary.get("Low", 0)}

## Improvement Suggestions

{format_improvements(improvements.get("suggestions", []))}

## Local Setup

1. Install the language runtimes and package managers used by this repository.
2. Install dependencies from the detected manifest files.
3. Create environment variables from existing `.env.example` files if present.
4. Run tests before making changes.

## Architecture

Open the Architecture page in AI Codebase Explainer to view generated Mermaid diagrams for service flow, dependency relationships, and API flow.

## Troubleshooting

- If indexing misses files, check ignore patterns and max file size settings.
- If AI answers are vague, rebuild embeddings with a stronger local embedding model.
- If local LLM responses fail, confirm Ollama is running and the selected model is pulled.
"""


def format_improvements(suggestions: list[dict[str, str]]) -> str:
    if not suggestions:
        return "- No improvement suggestions generated yet."
    return "\n".join(f"- **{item['severity']} / {item['category']}**: {item['recommendation']}" for item in suggestions)
